// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA90eOPda3zkGoJGkYZZDW53nkhO2iHdZk',
    appId: '1:552743686155:web:2c72aead8862e8f743f70e',
    messagingSenderId: '552743686155',
    projectId: 'hdcclinic-1c9e2',
    authDomain: 'hdcclinic-1c9e2.firebaseapp.com',
    storageBucket: 'hdcclinic-1c9e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB27uuOar_PMIMc_LWb7CMPN7NkMxykLxY',
    appId: '1:552743686155:android:1999bf274b6b969943f70e',
    messagingSenderId: '552743686155',
    projectId: 'hdcclinic-1c9e2',
    storageBucket: 'hdcclinic-1c9e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKg-6e3IpyVqfnhVnaXbxOJzBOZ8na7jw',
    appId: '1:552743686155:ios:e8d47d150c5175a143f70e',
    messagingSenderId: '552743686155',
    projectId: 'hdcclinic-1c9e2',
    storageBucket: 'hdcclinic-1c9e2.firebasestorage.app',
    iosBundleId: 'com.hdc.clinic.hdcClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKg-6e3IpyVqfnhVnaXbxOJzBOZ8na7jw',
    appId: '1:552743686155:ios:e8d47d150c5175a143f70e',
    messagingSenderId: '552743686155',
    projectId: 'hdcclinic-1c9e2',
    storageBucket: 'hdcclinic-1c9e2.firebasestorage.app',
    iosBundleId: 'com.hdc.clinic.hdcClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA90eOPda3zkGoJGkYZZDW53nkhO2iHdZk',
    appId: '1:552743686155:web:e59ac4d3e16bc29f43f70e',
    messagingSenderId: '552743686155',
    projectId: 'hdcclinic-1c9e2',
    authDomain: 'hdcclinic-1c9e2.firebaseapp.com',
    storageBucket: 'hdcclinic-1c9e2.firebasestorage.app',
  );
}
